import { EXPLANATION_SOURCE } from './constants.js';
import { escapeHtml } from './utils.js';

const VALID_SOURCES = new Set(Object.values(EXPLANATION_SOURCE));

const AI_WARNING_TEXT = 'Giải thích có thể không chính xác. Hãy hỏi giáo viên nếu bạn không chắc chắn.';

export function normalizeExplanationSource(value) {
    const v = String(value ?? '').trim();
    return VALID_SOURCES.has(v) ? v : '';
}

export function isAiExplanationSource(source) {
    const src = normalizeExplanationSource(source);
    return src === EXPLANATION_SOURCE.AI || src === EXPLANATION_SOURCE.AI_APPROVED;
}

const BADGE_LABEL_AI = 'Generated by AI';
const BADGE_LABEL_AI_NOT_REVIEWED = 'Generated by AI – not reviewed by teacher';
const BADGE_LABEL_AI_REVIEWED = 'Generated by AI – reviewed by teacher';
const BADGE_LABEL_TEACHER = 'Created by Teacher';

const ADMIN_BADGE = {
    [EXPLANATION_SOURCE.AI]: { label: BADGE_LABEL_AI, className: 'is-ai' },
    [EXPLANATION_SOURCE.AI_APPROVED]: { label: BADGE_LABEL_AI, className: 'is-ai-approved' },
    [EXPLANATION_SOURCE.TEACHER]: { label: BADGE_LABEL_TEACHER, className: 'is-teacher' }
};

function renderCertifiedIcon() {
    return '<i class="fas fa-circle-check explanation-source-certified-icon" aria-hidden="true"></i>';
}

function renderStudentBadge(label, { certified = false } = {}) {
    const icon = certified ? renderCertifiedIcon() : '';
    return `<span class="explanation-source-badge">${icon}${escapeHtml(label)}</span>`;
}

export function isAiReviewableSource(source) {
    const src = normalizeExplanationSource(source);
    return src === EXPLANATION_SOURCE.AI || src === EXPLANATION_SOURCE.AI_APPROVED;
}

export function getAdminExplanationBadgeInfo(source) {
    const src = normalizeExplanationSource(source);
    return ADMIN_BADGE[src] || { label: '', className: '' };
}

function renderAiWarningHelper() {
    return `<span class="explanation-source-help" tabindex="0" aria-label="${escapeHtml(AI_WARNING_TEXT)}">
        <span class="explanation-source-help-btn" aria-hidden="true">?</span>
        <span class="explanation-source-help-tip" role="tooltip">${escapeHtml(AI_WARNING_TEXT)}</span>
    </span>`;
}

/** Badge (+ optional ? helper) for student feedback header — top right. */
export function renderStudentExplanationHeaderMeta(source) {
    const src = normalizeExplanationSource(source);
    if (!src) return '';

    if (src === EXPLANATION_SOURCE.AI) {
        return `<div class="explanation-source-meta explanation-source-meta--ai">
            ${renderStudentBadge(BADGE_LABEL_AI_NOT_REVIEWED)}
            ${renderAiWarningHelper()}
        </div>`;
    }

    if (src === EXPLANATION_SOURCE.AI_APPROVED) {
        return `<div class="explanation-source-meta explanation-source-meta--ai-approved">
            ${renderStudentBadge(BADGE_LABEL_AI_REVIEWED, { certified: true })}
        </div>`;
    }

    return `<div class="explanation-source-meta explanation-source-meta--teacher">
        ${renderStudentBadge(BADGE_LABEL_TEACHER, { certified: true })}
    </div>`;
}

/** @deprecated Use renderStudentExplanationHeaderMeta in feedback header. */
export function renderStudentExplanationMeta(source) {
    return renderStudentExplanationHeaderMeta(source);
}

/** Wrap explanation body with source meta for student views. */
export function wrapStudentExplanationHtml(explanationHtml, source) {
    const body = String(explanationHtml ?? '').trim();
    if (!body) return '';
    const meta = renderStudentExplanationHeaderMeta(source);
    return `${meta}<div class="feedback-explanation-body rich-content">${body}</div>`;
}
